# Generated by Django 3.2.18 on 2023-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
