# Generated by Django 3.2.18 on 2023-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrackerApp', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('expire_data', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barcode', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=100)),
                ('recepe_text', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('recipe_id', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
