# Generated by Django 3.2.18 on 2023-04-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrackerApp', '0004_auto_20230411_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fridge',
            new_name='Frige',
        ),
    ]
